### ISSUE TITLE
Dealing with save size explosions from overpopulated characters?

### ISSUE THREAD

**Issue by steve02081504** [YAYA-shiori/yaya-dic#31] opened 2023-12-22 02:40 UTC
I wrote a kero adder last night to add one character per second:
https://github.com/steve02081504/kero-adder
Watching discord chat this morning I saw this:
```
💜 Zi  //watch out for scams — 今天04:25
good, good 😂 you have avoided the nightmare i once created for myself
don't uh. don't make characters with high numbers appear in YAYA, because YAYA will have to generate an array entry for them... in two arrays... which can bloat your save file a ton! because character 9000 has to be placed at array index 9000, which means 0-8999 have to be generated as empty elements if they don't exist, and... then they never go away :crylaugh:
```
I think this might be a fixable issue and easily triggered by jsstp.

**Comment by Zichqec** [comment] 2023-12-22 03:06
I rely on the arrays I mentioned for various things in my ghosts, it may break existing code to change them? 🤔 
It's definitely something that could be easily triggered by a number of sources though, even just mistakes in script input can make a ghost unusable until the save file is trimmed.
(I think so... it's been a long time since this happened)

**Comment by Zichqec** [comment] 2023-12-22 03:19
I replicated this on a duplicate SSP. These are the arrays that were filled with data:
SHIORI3FW.LastSurface
SHIORI3FW.IsVisible
SHIORI3FW.HWnd
SHIORI3FW.HWndOld
SHIORI3FW.BalloonHWnd

It seems as though the last 3 are erased when the ghost closes.
I tried this with \p[9000] and it was already very difficult for SSP to handle, and closing and reopening the ghost caused SSP to crash. It was even difficult for Notepad++ to display the contents of the variable file (The file is ~180k characters long with the ghost open, ~110k with the ghost closed). I imagine it would get exponentially worse with higher numbers.

**Comment by nikolat** [comment] 2023-12-22 10:08
How about defining an upper limit for array size in config.dic as follows?
```
#globaldefine SHIORI3FW.ARRAY_SIZE_TO_SAVE_MAX 1000
```
But is it possible to force the array size to be reduced when yaya.dll is unloaded?🤔

**Comment by steve02081504** [comment] 2023-12-22 10:19
Oddly enough I haven't stumbled across any array growth issues with Taromati2 + kero Adder
so I'm having trouble being vocal about this issue!
**steve out**

**Comment by nikolat** [comment] 2023-12-22 10:38
The problem can be easily reproduced.
Just run `\p[9000]` .
And this is not an SSTP matter.

**Comment by nikolat** [comment] 2023-12-22 10:43
I guess we can prevent the problem by not saving `SHIORI3FW.LastSurface` and `SHIORI3FW.IsVisible`.
That's easier.

**Closed** 2023-12-22 10:53 UTC
Labels: bug
